### ISSUE TITLE
python ..../setup.py looks for odoo_addons path in cwd instead of setup.py's location

### ISSUE THREAD

**Issue by realjo** [acsone/setuptools-odoo#1]
when calling setup.py from a different folder the installation will not work as it will look in the current folder for the odoo_addons folder instead of in the folder where setup.py is located:

bin/python ../src/odoo_myaddon/setup.py develop
Traceback (most recent call last):
  File "../src/odoo_myaddon/setup.py", line 5, in <module>
    odoo_addon=True,
  File "/somwhere/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/somewhere/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/somewhere/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/somewhere/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/somewhere/lib/python2.7/site-packages/setuptools_odoo/setup_keywords.py", line 28, in odoo_addon
    setup_keywords = prepare_odoo_addon()
  File "/somewhere/lib/python2.7/site-packages/setuptools_odoo/core.py", line 119, in prepare_odoo_addon
    addons = os.listdir(addons_dir)
OSError: [Errno 2] No such file or directory: 'odoo_addons'

I printed the current working dir just before the os.listdir call and its the current working directory where the command was called and not the directory where setup.py resides.

**Comment by sbidoul** [comment]
Thanks for testing setuptools_odoo!

Currently you must run setup.py from within it's directory. I think I read somewhere that in general running setup.py from outside it's directory was not supported by setuptools anyway, so I made no effort to work with paths relative to setup.py).

Is that a blocking issue for you?

**Comment by sbidoul** [comment]
@realjo I found the documentation saying that setup.py must be run from the distribution root.
https://docs.python.org/2/install/index.html#platform-variations

So I close this bug. Feel free to reopen if you think it's a real issue, of course.
