### ISSUE TITLE
Installing external dependencies from git

### ISSUE THREAD

**Issue by SimoRubi** [acsone/setuptools-odoo#54]
Hi,
I'm not 100% sure this is the right place to report the issue so please redirect me anywhere else if this is inappropriate.

We have implemented a module that depends on [openupgradelib](https://github.com/OCA/openupgradelib) and currently it is not uploaded to PyPI so we have to depend on the Git version of the library.

In order to do so, I've implemented https://github.com/OCA/l10n-italy/pull/2308 but Travis's build is failing:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/travis/build/OCA/l10n-italy/setup/l10n_it_vat_payability/setup.py", line 8, in <module>
        'openupgradelib': 'git+https://github.com/OCA/openupgradelib.git@master',
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.6.7/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/dist.py", line 464, in __init__
        self._finalize_requires()
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/dist.py", line 525, in _finalize_requires
        self._move_install_requirements_markers()
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/dist.py", line 564, in _move_install_requirements_markers
        inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
        yield Requirement(line)
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3094, in __init__
        super(Requirement, self).__init__(requirement_string)
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
        requirement_string[e.loc : e.loc + 8], e.msg
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected stringEnd
```
(from https://travis-ci.com/github/OCA/l10n-italy/jobs/510063896#L544-L564)

How can we implement this requirement?

Thanks!

**Comment by eLBati** [comment]
I think openupgradelib should be correctly pushed to pypi instead

**Comment by SimoRubi** [comment]
Yes that would fix the specific example I have brought, but fixing this issue would allow to install any Python library from VCS.
I haven't investigated this deeply yet but I don't see why this shouldn't work since it is supported from `pip` (https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support).

**Comment by sbidoul** [comment]
I answered on https://github.com/OCA/l10n-italy/pull/2308. In short, one must use the PEP 508 `package-name @ vcs-url` syntax.
