### ISSUE TITLE
i want fix this issue

### ISSUE THREAD

**Issue by simo338833** [acsone/setuptools-odoo#57]
C:\odoo1\odoo (14.0 -> origin)
λ python odoo-bin
Traceback (most recent call last):
  File "C:\odoo1\odoo\odoo-bin", line 5, in <module>
    import odoo
  File "C:\odoo1\odoo\odoo\__init__.py", line 75, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'

how can i fix this issue

**Comment by sbidoul** [comment]
You need to install pypdf2 which is a standard Odoo dependency IIRC. This problem is unrelated to this project, though, so closing.
